name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
      
    - name: make tst
      working-directory: ./tst
      run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
