name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install_gtest
      run: |
        sudo apt-get install libgtest-dev
        sudo apt-get install cmake # install cmake
        cd /usr/src/gtest
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        sudo make install
    
    - name: cmake_build
      run: |
        mkdir test_build
        cd test_build
        cmake ../test
        cmake --build .
        
    - name: run_tests
      run: ./test_build/TestBuild
