name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: cmake_test_build
      working-directory: ./test
      run: cmake ..
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
