name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: cmake_test_build
      run: cmake ./test
    - name: run_tests
      run: ./TestBuild
    #- name: make distcheck
    #  run: make distcheck
