name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: cmake_test_build
      run: |
        mkdir test_build
        cd test_build
        cmake ../test
        cmake --build
    - name: run_tests
      run: ./test_build/TestBuild
    #- name: make distcheck
    #  run: make distcheck
