name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
                
    - name: make_build
      run: |
        cd test
        make
        
    - name: run_tests
      run: |
        cd test
        ./TestBuild

    - name: install_avr_build_environment
      run: sudo apt-get install avr-libc binutils-avr gcc-avr avrdude
      
