name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install_gtest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        
    - name: cmake_build
      run: |
        mkdir test_build
        cd test_build
        cmake ../test
        cmake --build .
        
    - name: run_tests
      run: ./test_build/TestBuild
